# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProcessBar_Widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProcessBar_Widget(object):
    def setupUi(self, ProcessBar_Widget):
        ProcessBar_Widget.setObjectName("ProcessBar_Widget")
        ProcessBar_Widget.resize(1019, 172)
        self.horizontalLayout = QtWidgets.QHBoxLayout(ProcessBar_Widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(ProcessBar_Widget)
        self.widget.setMinimumSize(QtCore.QSize(0, 150))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 150))
        self.widget.setAutoFillBackground(True)
        self.widget.setStyleSheet("font-family:\"Times New Roman\";\n"
"")
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_thumPic = QtWidgets.QFrame(self.widget)
        self.frame_thumPic.setMinimumSize(QtCore.QSize(100, 100))
        self.frame_thumPic.setMaximumSize(QtCore.QSize(100, 100))
        self.frame_thumPic.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_thumPic.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_thumPic.setObjectName("frame_thumPic")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_thumPic)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_thumbPic = QtWidgets.QLabel(self.frame_thumPic)
        self.label_thumbPic.setText("")
        self.label_thumbPic.setObjectName("label_thumbPic")
        self.verticalLayout_2.addWidget(self.label_thumbPic)
        self.horizontalLayout_2.addWidget(self.frame_thumPic)
        self.frame_process = QtWidgets.QFrame(self.widget)
        self.frame_process.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_process.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_process.setObjectName("frame_process")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_process)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_videoTitle = QtWidgets.QLabel(self.frame_process)
        self.label_videoTitle.setObjectName("label_videoTitle")
        self.horizontalLayout_3.addWidget(self.label_videoTitle)
        self.label_duration = QtWidgets.QLabel(self.frame_process)
        self.label_duration.setObjectName("label_duration")
        self.horizontalLayout_3.addWidget(self.label_duration)
        self.label_method = QtWidgets.QLabel(self.frame_process)
        self.label_method.setObjectName("label_method")
        self.horizontalLayout_3.addWidget(self.label_method)
        self.label_doneSize = QtWidgets.QLabel(self.frame_process)
        self.label_doneSize.setObjectName("label_doneSize")
        self.horizontalLayout_3.addWidget(self.label_doneSize)
        self.label_speed = QtWidgets.QLabel(self.frame_process)
        self.label_speed.setObjectName("label_speed")
        self.horizontalLayout_3.addWidget(self.label_speed)
        self.server_id = QtWidgets.QLabel(self.frame_process)
        self.server_id.setObjectName("server_id")
        self.horizontalLayout_3.addWidget(self.server_id)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.progressBar = QtWidgets.QProgressBar(self.frame_process)
        self.progressBar.setStyleSheet("QProgressBar{\n"
"        border: none;\n"
"        color: black;\n"
"        text-align: center;\n"
"        background: rgb(238, 238, 240);\n"
"}\n"
"QProgressBar::chunk {\n"
"        border: none;\n"
"        background: rgb(255, 177, 132);\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.label_bit = QtWidgets.QLabel(self.frame_process)
        self.label_bit.setObjectName("label_bit")
        self.verticalLayout.addWidget(self.label_bit)
        self.horizontalLayout_2.addWidget(self.frame_process)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(ProcessBar_Widget)
        QtCore.QMetaObject.connectSlotsByName(ProcessBar_Widget)

    def retranslateUi(self, ProcessBar_Widget):
        _translate = QtCore.QCoreApplication.translate
        ProcessBar_Widget.setWindowTitle(_translate("ProcessBar_Widget", "Form"))
        self.label_videoTitle.setText(_translate("ProcessBar_Widget", "视频名称"))
        self.label_duration.setText(_translate("ProcessBar_Widget", "时长"))
        self.label_method.setText(_translate("ProcessBar_Widget", "解密方法"))
        self.label_doneSize.setText(_translate("ProcessBar_Widget", "已下载"))
        self.label_speed.setText(_translate("ProcessBar_Widget", "下载速度"))
        self.server_id.setText(_translate("ProcessBar_Widget", "server_id"))
        self.label_bit.setText(_translate("ProcessBar_Widget", "比特率"))
